/**
 * DAILY CONTENT DATABASE
 */

const DAILY_TIPS = [
    // === GRAMMAR BASICS (1-15) ===
    { title: "It's vs. Its", content: "'It's' is a contraction for 'it is' or 'it has'. 'Its' shows possession (like 'his')." },
    { title: "Fewer vs. Less", content: "Use 'fewer' for things you can count (fewer apples). Use 'less' for things you can't count (less water)." },
    { title: "Their, There, They're", content: "'Their' shows possession. 'There' refers to a place. 'They're' means 'they are'." },
    { title: "Your vs. You're", content: "'Your' shows possession (your book). 'You're' is a contraction for 'you are'." },
    { title: "Effect vs. Affect", content: "'Affect' is usually a verb meaning to influence. 'Effect' is usually a noun meaning the result." },
    { title: "Then vs. Than", content: "'Then' relates to time (first this, then that). 'Than' is used for comparisons (better than)." },
    { title: "Who vs. Whom", content: "'Who' is the subject doing the action. 'Whom' is the object receiving the action. Tip: replace with he/she vs. him/her." },
    { title: "Lay vs. Lie", content: "'Lay' needs an object (lay the book down). 'Lie' doesn't (lie down on the bed)." },
    { title: "Me vs. I", content: "Use 'I' for the subject, 'me' for the object. Remove the other person to check: 'She went with John and me' → 'She went with me' ✓" },
    { title: "Who's vs. Whose", content: "'Who's' means 'who is' or 'who has'. 'Whose' shows possession (whose book is this?)." },
    { title: "Principal vs. Principle", content: "'Principal' means main or a school head (the principal is your pal). 'Principle' is a fundamental truth or belief." },
    { title: "Complement vs. Compliment", content: "'Complement' completes something (wine complements cheese). 'Compliment' is praise (nice compliment)." },
    { title: "Stationary vs. Stationery", content: "'Stationary' means not moving. 'Stationery' is writing paper (remember: e for envelope)." },
    { title: "Capital vs. Capitol", content: "'Capital' is a city, money, or uppercase letter. 'Capitol' is specifically a government building." },
    { title: "Accept vs. Except", content: "'Accept' means to receive willingly. 'Except' means excluding (everyone except John)." },

    // === PUNCTUATION (16-25) ===
    { title: "Oxford Comma", content: "The serial comma before 'and' in a list prevents ambiguity: 'I love my parents, Oprah, and Jesus' vs. 'I love my parents, Oprah and Jesus'." },
    { title: "Semicolon Usage", content: "Use semicolons to connect related independent clauses without a conjunction: 'I love coffee; it keeps me awake.'" },
    { title: "Colon Usage", content: "Use colons to introduce lists, explanations, or quotes. What follows explains what came before." },
    { title: "Em Dash vs. En Dash", content: "Em dash (—) emphasizes or separates thoughts. En dash (–) shows ranges (2020–2024)." },
    { title: "Hyphen in Compound Words", content: "Use hyphens to avoid ambiguity: 'man-eating shark' vs. 'man eating shark.' Hyphenate compound adjectives before nouns." },
    { title: "Apostrophe Rules", content: "Use apostrophes for possession (John's book) and contractions (don't). NOT for plurals: 'The Smiths' not 'The Smith's'." },
    { title: "Quotation Marks with Punctuation", content: "In American English, periods and commas go inside quotes. In British English, they go outside unless part of the quote." },
    { title: "Ellipsis Usage", content: "Use three dots (...) to show omitted text or a trailing thought. Four dots if the omission includes a period." },
    { title: "Comma Splices", content: "Don't join two complete sentences with just a comma. Use a period, semicolon, or conjunction instead." },
    { title: "Parentheses Placement", content: "Put periods outside parentheses if the content is a fragment. Put inside if it's a complete sentence." },

    // === COMMON MISTAKES (26-40) ===
    { title: "Could of vs. Could Have", content: "Always use 'could have', 'should have', 'would have' – never 'could of'. The contraction 'could've' causes this confusion." },
    { title: "Double Negatives", content: "Avoid double negatives in formal English: 'I don't know nothing' should be 'I don't know anything' or 'I know nothing.'" },
    { title: "Alot vs. A Lot", content: "'A lot' is always two words meaning many. 'Alot' is not a word. 'Allot' means to distribute." },
    { title: "Anyway vs. Anyways", content: "'Anyway' is standard. 'Anyways' is informal and considered non-standard in formal writing." },
    { title: "Supposedly vs. Supposably", content: "'Supposedly' means allegedly or presumably. 'Supposably' is rare and means 'imaginably.'" },
    { title: "Irregardless", content: "'Irregardless' is non-standard. Use 'regardless' instead. The extra 'ir-' is redundant since 'less' already makes it negative." },
    { title: "Literally vs. Figuratively", content: "'Literally' means actually happened. Don't use it for emphasis: 'I literally died' is incorrect unless you actually died." },
    { title: "I Could Care Less", content: "The correct phrase is 'I couldn't care less.' If you could care less, you still care somewhat." },
    { title: "Peace of Mind vs. Piece of Mind", content: "'Peace of mind' means calmness. 'Piece of my mind' means telling someone off angrily." },
    { title: "Nip It in the Bud", content: "The correct idiom is 'nip it in the bud' (stop early like trimming a plant), not 'nip it in the butt.'" },
    { title: "For All Intents and Purposes", content: "The phrase is 'for all intents and purposes,' not 'for all intensive purposes.'" },
    { title: "One and the Same", content: "The correct phrase is 'one and the same,' not 'one in the same.'" },
    { title: "Case Sensitive Words", content: "'I' as a pronoun is always capitalized. Proper nouns need capitals. Don't capitalize random words for emphasis." },
    { title: "i.e. vs. e.g.", content: "'i.e.' means 'that is' (clarifying). 'e.g.' means 'for example' (illustrating). They're not interchangeable." },
    { title: "Into vs. In To", content: "'Into' shows movement (walk into the room). 'In to' is two words where 'in' is part of the verb (come in to eat)." },

    // === VOCABULARY TIPS (41-55) ===
    { title: "Unique is Absolute", content: "Something is either unique or not unique – avoid 'very unique' or 'most unique.' Use 'unusual' or 'rare' instead." },
    { title: "Enormity vs. Enormous", content: "'Enormity' means great evil or wickedness. 'Enormous' means very large. Don't use enormity for size." },
    { title: "Bemused vs. Amused", content: "'Bemused' means confused, not amused. They sound similar but have very different meanings." },
    { title: "Disinterested vs. Uninterested", content: "'Disinterested' means impartial or unbiased. 'Uninterested' means not interested. A judge should be disinterested, not uninterested." },
    { title: "Fortuitous vs. Fortunate", content: "'Fortuitous' means happening by chance. 'Fortunate' means lucky. They're not synonyms." },
    { title: "Verbal vs. Oral", content: "'Verbal' means using words (written or spoken). 'Oral' specifically means spoken. All oral is verbal, not vice versa." },
    { title: "Novel vs. New", content: "'Novel' means new AND unusual or innovative. Not just 'new.' A novel approach is creative, not just recent." },
    { title: "Notorious vs. Famous", content: "'Notorious' means famous for something bad. Don't use it as a positive. Use 'famous' or 'renowned' instead." },
    { title: "Imply vs. Infer", content: "The speaker implies (suggests). The listener infers (concludes). You infer FROM something." },
    { title: "Nauseous vs. Nauseated", content: "'Nauseous' means causing nausea. 'Nauseated' means feeling sick. You feel nauseated, not nauseous." },
    { title: "Ultimate", content: "'Ultimate' means last or final, not best. 'The ultimate decision' means the final one, not necessarily the greatest." },
    { title: "Bimonthly Ambiguity", content: "'Bimonthly' can mean twice a month OR every two months. Clarify which you mean to avoid confusion." },
    { title: "Presently vs. Currently", content: "'Presently' traditionally means 'soon.' 'Currently' means 'now.' Usage is shifting, but be aware of the distinction." },
    { title: "Anxious vs. Eager", content: "'Anxious' implies worry or fear. 'Eager' implies excitement. Be eager for good things, anxious about uncertain ones." },
    { title: "Consist of vs. Comprise", content: "'Comprise' means 'consist of' – don't say 'comprised of.' The whole comprises its parts." },

    // === WRITING TIPS (56-70) ===
    { title: "Active vs. Passive Voice", content: "Active voice is clearer: 'The dog bit the man' vs. 'The man was bitten by the dog.' Use passive when the actor is unknown or unimportant." },
    { title: "Concise Writing", content: "Eliminate redundant phrases: 'each and every' → 'each'; 'basic fundamentals' → 'fundamentals'; 'past history' → 'history.'" },
    { title: "Strong Verbs", content: "Replace weak verb + adverb with strong verb: 'ran quickly' → 'sprinted'; 'said softly' → 'whispered.'" },
    { title: "Starting Sentences with And/But", content: "It's perfectly acceptable to start sentences with 'And' or 'But' for emphasis. Just don't overdo it." },
    { title: "Ending with Prepositions", content: "Ending sentences with prepositions is natural: 'What are you looking for?' is better than 'For what are you looking?'" },
    { title: "Sentence Variety", content: "Vary sentence length and structure. Mix short punchy sentences with longer, flowing ones for rhythm." },
    { title: "Show, Don't Tell", content: "Instead of 'He was angry,' write 'His fists clenched, and his face turned red.' Let readers experience the emotion." },
    { title: "Avoid Clichés", content: "Replace overused phrases: 'at the end of the day' → 'ultimately'; 'think outside the box' → 'think creatively.'" },
    { title: "Nominalizations", content: "Turn nouns back into verbs for stronger writing: 'reached a conclusion' → 'concluded'; 'made a decision' → 'decided.'" },
    { title: "Parallel Structure", content: "Keep elements in a list parallel: 'She likes reading, writing, and to swim' should be 'reading, writing, and swimming.'" },
    { title: "Avoid Weak Openers", content: "Avoid starting sentences with 'There is/are' or 'It is.' They weaken your writing: 'There are many people' → 'Many people...'" },
    { title: "Concrete Language", content: "Use specific details: 'The car' → 'the rusted 1990s sedan'; 'food' → 'steaming lasagna.' Details create vivid images." },
    { title: "Transitional Words", content: "Use transitions to connect ideas: 'however,' 'therefore,' 'moreover,' 'in contrast.' They guide readers through your logic." },
    { title: "The Power of Three", content: "Lists of three are memorable: 'Life, liberty, and the pursuit of happiness.' Use this technique for emphasis." },
    { title: "Read Aloud", content: "Reading your writing aloud reveals awkward phrasing, run-on sentences, and rhythm problems you might miss when reading silently." },

    // === PRONUNCIATION TIPS (71-80) ===
    { title: "Silent Letters", content: "Many English words have silent letters: 'knife' (silent k), 'island' (silent s), 'Wednesday' (silent d), 'receipt' (silent p)." },
    { title: "Words with Different Stress", content: "Some words change meaning with stress: 'REcord' (noun) vs. 'reCORD' (verb); 'PREsent' vs. 'preSENT.'" },
    { title: "The 'GH' Problem", content: "'GH' has many sounds: 'enough' (f), 'ghost' (g), 'through' (silent). There's no rule – memorize each word." },
    { title: "Ough Combinations", content: "'Ough' has many sounds: though (o), through (oo), rough (uff), cough (off), thought (aw), bough (ow)." },
    { title: "Common Mispronounced Words", content: "'Epitome' (eh-PIT-uh-mee), 'hyperbole' (hi-PER-buh-lee), 'mischievous' (MIS-chiv-us), 'espresso' (not expresso)." },
    { title: "Schwa Sound", content: "The schwa (ə) is the most common English sound – a weak 'uh' in unstressed syllables: 'about' = 'uh-BOUT.'" },
    { title: "Homophones", content: "Words that sound the same but differ in meaning: 'to/too/two,' 'their/there/they're,' 'hear/here.' Context is key." },
    { title: "Homographs", content: "Words spelled the same but pronounced differently: 'wind' (air movement) vs. 'wind' (to turn); 'tear' (crying) vs. 'tear' (rip)." },
    { title: "Silent E Rule", content: "Silent E makes the preceding vowel say its name: 'hat' vs. 'hate,' 'kit' vs. 'kite,' 'hop' vs. 'hope.'" },
    { title: "Consonant Doubling", content: "Double consonants often make the preceding vowel short: 'latter' vs. 'later,' 'dinner' vs. 'diner.'" },

    // === LANGUAGE LEARNING TIPS (81-90) ===
    { title: "Context Over Memorization", content: "Learn words in sentences, not isolation. Context helps you remember meaning and usage naturally." },
    { title: "Immersion Technique", content: "Surround yourself with English: change your phone language, watch English content, think in English." },
    { title: "Shadowing Practice", content: "Listen to native speakers and repeat simultaneously. This improves pronunciation, rhythm, and intonation." },
    { title: "Keep a Vocabulary Journal", content: "Write new words with example sentences, not just definitions. Review regularly using spaced repetition." },
    { title: "Learn Word Families", content: "Learn related words together: act, action, active, actively, activity. This multiplies your vocabulary." },
    { title: "Prefix and Suffix Power", content: "Understanding prefixes (un-, re-, pre-) and suffixes (-tion, -able, -ness) helps you decode new words." },
    { title: "Phrasal Verbs Are Essential", content: "Native speakers use phrasal verbs constantly: 'give up,' 'look forward to,' 'run out of.' Learn them in context." },
    { title: "Collocations Matter", content: "Some words naturally go together: 'make a decision' (not 'do a decision'), 'take a break' (not 'make a break')." },
    { title: "Don't Fear Mistakes", content: "Mistakes are essential for learning. Each error is an opportunity to improve. Speak without fear of perfection." },
    { title: "Consistent Practice", content: "15 minutes daily beats 2 hours weekly. Regular exposure keeps your brain engaged with the language." },
];

const VOCABULARY_POOL = [
    // === A (Words 1-65) ===
    { word: "Abate", definition: "To become less intense or widespread." },
    { word: "Aberration", definition: "A departure from what is normal or expected." },
    { word: "Abhor", definition: "To regard with disgust and hatred." },
    { word: "Abide", definition: "To accept or act in accordance with a rule or decision." },
    { word: "Ablution", definition: "The act of washing oneself; a ceremonial washing." },
    { word: "Abnegation", definition: "The act of renouncing or rejecting something." },
    { word: "Abolish", definition: "To formally put an end to a system or practice." },
    { word: "Abominable", definition: "Causing moral revulsion; detestable." },
    { word: "Aboriginal", definition: "Relating to the original inhabitants of a land." },
    { word: "Abrasive", definition: "Rough to the touch; showing little concern for others' feelings." },
    { word: "Abreast", definition: "Side by side and facing the same way." },
    { word: "Abridge", definition: "To shorten a text while keeping the main points." },
    { word: "Abrogate", definition: "To evade or annul a responsibility or obligation." },
    { word: "Abscond", definition: "To leave hurriedly and secretly to escape detection." },
    { word: "Absolution", definition: "Formal release from guilt or punishment." },
    { word: "Abstain", definition: "To restrain oneself from doing something." },
    { word: "Abstemious", definition: "Not self-indulgent, especially in food and drink." },
    { word: "Abstract", definition: "Existing in thought but not having a physical existence." },
    { word: "Abstruse", definition: "Difficult to understand; obscure." },
    { word: "Abundant", definition: "Existing in large quantities; plentiful." },
    { word: "Abysmal", definition: "Extremely bad; appalling." },
    { word: "Acclaim", definition: "To praise enthusiastically and publicly." },
    { word: "Acclimate", definition: "To become accustomed to a new climate or environment." },
    { word: "Accolade", definition: "An award or privilege granted as a special honor." },
    { word: "Accommodate", definition: "To provide lodging or sufficient space for." },
    { word: "Accomplice", definition: "A person who helps another commit a crime." },
    { word: "Accord", definition: "To give someone power or recognition." },
    { word: "Accost", definition: "To approach and speak to someone aggressively." },
    { word: "Accoutrement", definition: "An additional item of dress or equipment." },
    { word: "Accrue", definition: "To accumulate over time." },
    { word: "Accumulate", definition: "To gather or collect over time." },
    { word: "Accurate", definition: "Correct in all details; exact." },
    { word: "Accusation", definition: "A charge or claim that someone has done something wrong." },
    { word: "Acquiesce", definition: "To accept something reluctantly without protest." },
    { word: "Acquittal", definition: "A judgment that someone is not guilty of a crime." },
    { word: "Acrimonious", definition: "Angry and bitter in tone or manner." },
    { word: "Acumen", definition: "The ability to make good judgments and quick decisions." },
    { word: "Adage", definition: "A proverb or short statement expressing a general truth." },
    { word: "Adamant", definition: "Refusing to be persuaded or change one's mind." },
    { word: "Adapt", definition: "To change to suit different conditions." },
    { word: "Adaptive", definition: "Able to adjust to new conditions." },
    { word: "Addendum", definition: "An item of additional material added at the end of a book." },
    { word: "Adhere", definition: "To stick to or follow a rule or belief." },
    { word: "Adherent", definition: "Someone who supports a particular party or belief." },
    { word: "Adjacent", definition: "Next to or adjoining something else." },
    { word: "Adjudge", definition: "To give a formal judgment or decision." },
    { word: "Adjudicate", definition: "To make a formal judgment on a disputed matter." },
    { word: "Adjunct", definition: "Something added to something else as supplementary." },
    { word: "Admonish", definition: "To warn or reprimand someone firmly." },
    { word: "Adornment", definition: "Something that adds beauty or decoration." },
    { word: "Adroit", definition: "Clever or skillful in using the hands or mind." },
    { word: "Adulation", definition: "Excessive admiration or praise." },
    { word: "Adulterate", definition: "To make impure by adding inferior substances." },
    { word: "Advent", definition: "The arrival of a notable person or event." },
    { word: "Adversary", definition: "One's opponent in a contest or conflict." },
    { word: "Adverse", definition: "Unfavorable or harmful." },
    { word: "Adversity", definition: "Difficulties or misfortune." },
    { word: "Advocate", definition: "To publicly recommend or support." },
    { word: "Aegis", definition: "Protection or support from someone or something." },
    { word: "Aesthetic", definition: "Concerned with beauty or artistic taste." },
    { word: "Affable", definition: "Friendly, good-natured, or easy to talk to." },
    { word: "Affect", definition: "To influence or make a difference to." },
    { word: "Affection", definition: "A gentle feeling of fondness or liking." },

    // === B (Words 66-130) ===
    { word: "Babble", definition: "To talk rapidly and continuously in a foolish way." },
    { word: "Baconian", definition: "Relating to Francis Bacon or his philosophy." },
    { word: "Badger", definition: "To pester or harass someone persistently." },
    { word: "Baffle", definition: "To totally bewilder or perplex." },
    { word: "Bagatelle", definition: "A thing of little importance or value." },
    { word: "Bailiwick", definition: "One's sphere of operations or area of expertise." },
    { word: "Balanced", definition: "Taking everything into account; fairly judged." },
    { word: "Baleful", definition: "Threatening harm or evil; menacing." },
    { word: "Balk", definition: "To hesitate or be unwilling to accept something." },
    { word: "Ballad", definition: "A poem or song telling a story in short stanzas." },
    { word: "Banal", definition: "Lacking originality; boring and obvious." },
    { word: "Banality", definition: "The fact or condition of being commonplace." },
    { word: "Banana", definition: "A long curved fruit with a yellow rind." },
    { word: "Baneful", definition: "Causing great distress or harm." },
    { word: "Banish", definition: "To send someone away from a place as punishment." },
    { word: "Bankrupt", definition: "Declared in law as unable to pay debts." },
    { word: "Banquet", definition: "An elaborate formal meal for many people." },
    { word: "Barbarian", definition: "A person who is savage or uncivilized." },
    { word: "Barbarous", definition: "Extremely cruel and unpleasant." },
    { word: "Bard", definition: "A poet, traditionally one reciting epics." },
    { word: "Barefaced", definition: "Shameless and undisguised; bold." },
    { word: "Bargain", definition: "An agreement between parties on price." },
    { word: "Baroque", definition: "Highly ornate and extravagant in style." },
    { word: "Barrage", definition: "A concentrated artillery bombardment." },
    { word: "Barrier", definition: "Something that blocks or obstructs movement." },
    { word: "Barter", definition: "To exchange goods or services for other goods." },
    { word: "Baseless", definition: "Without foundation in fact or reality." },
    { word: "Basilica", definition: "A large and important church." },
    { word: "Bask", definition: "To lie exposed to warmth and light for relaxation." },
    { word: "Bastion", definition: "A stronghold or fortified place." },
    { word: "Bathos", definition: "An anticlimax created by a lapse in mood." },
    { word: "Batten", definition: "To thrive or prosper at another's expense." },
    { word: "Bauble", definition: "A small, showy, and usually cheap ornament." },
    { word: "Bawdy", definition: "Dealing with sexual matters in a humorous way." },
    { word: "Bayou", definition: "A marshy outlet of a lake or river." },
    { word: "Beacon", definition: "A light serving as a guide or warning." },
    { word: "Beatitude", definition: "Supreme blessedness or happiness." },
    { word: "Bedlam", definition: "A scene of wild confusion and uproar." },
    { word: "Bedrock", definition: "The fundamental principles on which something is based." },
    { word: "Befuddle", definition: "To make someone unable to think clearly." },
    { word: "Begrudge", definition: "To give reluctantly or resentfully." },
    { word: "Behemoth", definition: "Something enormous in size or power." },
    { word: "Beholden", definition: "Owing thanks or gratitude to someone." },
    { word: "Beholder", definition: "A person who sees or observes something." },
    { word: "Beleaguer", definition: "To cause problems or difficulties for someone." },
    { word: "Belie", definition: "To fail to give a true impression of something." },
    { word: "Belittle", definition: "To dismiss as unimportant or inferior." },
    { word: "Bellicose", definition: "Demonstrating aggression and willingness to fight." },
    { word: "Belligerent", definition: "Hostile and aggressive." },
    { word: "Bemoan", definition: "To express sorrow or disapproval of." },
    { word: "Bemused", definition: "Puzzled, confused, or bewildered." },
    { word: "Beneath", definition: "Extending or directly underneath." },
    { word: "Benediction", definition: "A prayer asking for divine blessing." },
    { word: "Benefactor", definition: "A person who gives money for a good cause." },
    { word: "Beneficial", definition: "Favorable or advantageous; helpful." },
    { word: "Beneficiary", definition: "A person who derives advantage from something." },
    { word: "Benevolent", definition: "Well-meaning and kindly." },
    { word: "Benign", definition: "Gentle and kindly; not harmful." },
    { word: "Bent", definition: "Determined to do something; resolved." },
    { word: "Bequeath", definition: "To pass something on to another by will." },
    { word: "Berate", definition: "To scold or criticize angrily." },
    { word: "Bereave", definition: "To deprive someone of a loved one through death." },

    // === C (Words 131-215) ===
    { word: "Cacophony", definition: "A harsh, discordant mixture of sounds." },
    { word: "Cadaverous", definition: "Resembling a corpse; pale and gaunt." },
    { word: "Cajole", definition: "To persuade someone by flattery or coaxing." },
    { word: "Calamity", definition: "An event causing great damage or suffering." },
    { word: "Calculate", definition: "To determine mathematically or by reasoning." },
    { word: "Caldron", definition: "A large pot for boiling or cooking." },
    { word: "Callow", definition: "Inexperienced and immature." },
    { word: "Calumny", definition: "The making of false statements to damage reputation." },
    { word: "Camouflage", definition: "The disguising of something to blend with surroundings." },
    { word: "Candid", definition: "Truthful and straightforward; frank." },
    { word: "Candor", definition: "The quality of being open and honest." },
    { word: "Canine", definition: "Relating to or resembling a dog." },
    { word: "Canny", definition: "Having good judgment; shrewd." },
    { word: "Canonical", definition: "Accepted as being authentic or authoritative." },
    { word: "Canvass", definition: "To solicit votes, subscriptions, or opinions." },
    { word: "Capable", definition: "Having the ability or quality to do something." },
    { word: "Capacious", definition: "Having a lot of space; roomy." },
    { word: "Capitulate", definition: "To cease resisting an opponent; surrender." },
    { word: "Caprice", definition: "A sudden and unaccountable change of mood." },
    { word: "Capricious", definition: "Given to sudden changes of mood or behavior." },
    { word: "Captious", definition: "Tending to find fault at every opportunity." },
    { word: "Captivate", definition: "To attract and hold the interest of." },
    { word: "Captivity", definition: "The condition of being imprisoned or confined." },
    { word: "Carapace", definition: "The hard upper shell of a turtle or crustacean." },
    { word: "Carcass", definition: "The dead body of an animal." },
    { word: "Cardinal", definition: "Of the greatest importance; fundamental." },
    { word: "Careen", definition: "To move swiftly in an uncontrolled way." },
    { word: "Careful", definition: "Exercising caution; avoiding potential danger." },
    { word: "Caress", definition: "To touch or stroke gently or lovingly." },
    { word: "Caricature", definition: "A distorted representation through exaggeration." },
    { word: "Carnage", definition: "The killing of many people; mass slaughter." },
    { word: "Carnal", definition: "Relating to physical and especially sexual desires." },
    { word: "Carnivorous", definition: "Feeding on other animals." },
    { word: "Carousal", definition: "A noisy drinking party or revelry." },
    { word: "Carp", definition: "To complain or find fault continually." },
    { word: "Carrion", definition: "Decaying flesh of dead animals." },
    { word: "Carriage", definition: "A four-wheeled horse-drawn vehicle." },
    { word: "Carve", definition: "To cut into pieces or a desired shape." },
    { word: "Cascade", definition: "A small waterfall descending in stages." },
    { word: "Castigate", definition: "To reprimand someone severely." },
    { word: "Casual", definition: "Relaxed and unconcerned; not formal." },
    { word: "Casualty", definition: "A person killed or injured in war or accident." },
    { word: "Cataclysm", definition: "A large-scale and violent event causing upheaval." },
    { word: "Catalyst", definition: "Something that causes an important event or change." },
    { word: "Catapult", definition: "To hurl or launch something with great force." },
    { word: "Cataract", definition: "A large waterfall; also an eye condition." },
    { word: "Catastrophe", definition: "A sudden event causing great damage or suffering." },
    { word: "Catechism", definition: "A summary of religious doctrine in Q&A form." },
    { word: "Categorical", definition: "Unconditional; absolute; without exception." },
    { word: "Cater", definition: "To provide food and drink for an event." },
    { word: "Catharsis", definition: "The process of releasing strong emotions." },
    { word: "Cathartic", definition: "Providing psychological relief through expression." },
    { word: "Caucus", definition: "A meeting of members of a political party." },
    { word: "Caudal", definition: "Relating to the tail or posterior." },
    { word: "Caustic", definition: "Sarcastic in a scathing and bitter way." },
    { word: "Caution", definition: "Care taken to avoid danger or mistakes." },
    { word: "Cavalier", definition: "Showing lack of proper concern; dismissive." },
    { word: "Caveat", definition: "A warning or proviso about a statement." },
    { word: "Cavernous", definition: "Like a cavern in being vast and deep." },
    { word: "Cavil", definition: "To make petty objections; raise trivial objections." },
    { word: "Cease", definition: "To bring or come to an end." },
    { word: "Cede", definition: "To give up power or territory." },
    { word: "Celestial", definition: "Relating to the sky or heaven." },
    { word: "Celerity", definition: "Swiftness of movement; speed." },
    { word: "Celebrate", definition: "To acknowledge a significant event with enjoyment." },
    { word: "Censure", definition: "To express severe disapproval of someone." },
    { word: "Census", definition: "An official count of a population." },
    { word: "Centennial", definition: "Relating to a hundredth anniversary." },
    { word: "Central", definition: "Of greatest importance; principal or essential." },
    { word: "Centrifugal", definition: "Moving away from a center; radiating." },
    { word: "Centripetal", definition: "Moving toward a center." },
    { word: "Cerebral", definition: "Relating to the brain; intellectual rather than emotional." },
    { word: "Ceremonial", definition: "Relating to or used for formal events." },
    { word: "Ceremonious", definition: "Having or showing elaborate attention to formality." },
    { word: "Certainty", definition: "Firm conviction that something is true." },
    { word: "Certify", definition: "To confirm formally as true or accurate." },
    { word: "Cessation", definition: "The fact or process of ending." },
    { word: "Chafe", definition: "To become or make annoyed or impatient." },
    { word: "Chaff", definition: "Worthless things; husks separated from grain." },
    { word: "Chagrin", definition: "Annoyance or distress at having failed." },
    { word: "Chameleon", definition: "One who changes opinions to suit circumstances." },
    { word: "Champion", definition: "To support the cause of; defend." },
    { word: "Chaos", definition: "Complete disorder and confusion." },
    { word: "Chaperone", definition: "A person who supervises the young or unmarried." },

    // === D (Words 216-290) ===
    { word: "Dabble", definition: "To take part in an activity in a casual way." },
    { word: "Dainty", definition: "Delicate and pretty; fastidious." },
    { word: "Dally", definition: "To waste time; dawdle." },
    { word: "Dampen", definition: "To make less strong or intense." },
    { word: "Dandy", definition: "A man devoted to style and fashion." },
    { word: "Dangle", definition: "To hang loosely or swing freely." },
    { word: "Dank", definition: "Unpleasantly damp and cold." },
    { word: "Dapper", definition: "Neat and trim in dress and appearance." },
    { word: "Dappled", definition: "Marked with spots or patches of color." },
    { word: "Daredevil", definition: "A reckless person who enjoys danger." },
    { word: "Daring", definition: "Adventurous or audaciously bold." },
    { word: "Darling", definition: "A person who is greatly loved." },
    { word: "Dashing", definition: "Attractive, adventurous, and full of confidence." },
    { word: "Daunt", definition: "To make someone feel intimidated." },
    { word: "Dauntless", definition: "Showing fearlessness and determination." },
    { word: "Dawn", definition: "The first appearance of light in the morning." },
    { word: "Daze", definition: "To make someone unable to think clearly." },
    { word: "Dazzle", definition: "To blind temporarily by sudden excessive light." },
    { word: "Deadlock", definition: "A situation where no progress can be made." },
    { word: "Deadly", definition: "Causing or able to cause death." },
    { word: "Deafening", definition: "Extremely noisy; overwhelmingly loud." },
    { word: "Dealing", definition: "The conduct of business or trade." },
    { word: "Dean", definition: "The head of a college or university faculty." },
    { word: "Dear", definition: "Regarded with deep affection; expensive." },
    { word: "Dearth", definition: "A scarcity or lack of something." },
    { word: "Debase", definition: "To reduce the quality or value of something." },
    { word: "Debacle", definition: "A sudden and ignominious failure; a disaster." },
    { word: "Debate", definition: "To discuss opposing points; argue." },
    { word: "Debilitate", definition: "To make someone weak and infirm." },
    { word: "Debonair", definition: "Confident, stylish, and charming." },
    { word: "Debris", definition: "Scattered pieces of rubbish or remains." },
    { word: "Debut", definition: "A first public appearance or performance." },
    { word: "Decade", definition: "A period of ten years." },
    { word: "Decadence", definition: "Moral or cultural decline." },
    { word: "Decadent", definition: "Characterized by moral or cultural decline." },
    { word: "Decapitate", definition: "To cut off the head of someone." },
    { word: "Decay", definition: "To become rotten; decline in quality." },
    { word: "Decease", definition: "A person's death." },
    { word: "Deceit", definition: "The action of deceiving someone." },
    { word: "Deceive", definition: "To cause someone to believe something false." },
    { word: "Decent", definition: "Conforming with generally accepted standards." },
    { word: "Decentralize", definition: "To move power away from a central authority." },
    { word: "Decipher", definition: "To interpret or make sense of something difficult." },
    { word: "Decision", definition: "A conclusion reached after consideration." },
    { word: "Decisive", definition: "Settling an issue; producing a definite result." },
    { word: "Deck", definition: "A structure providing an outdoor floor area." },
    { word: "Declaim", definition: "To utter or deliver a speech formally." },
    { word: "Decline", definition: "To become smaller or less in amount." },
    { word: "Decoction", definition: "A liquor obtained by boiling something." },
    { word: "Decode", definition: "To interpret a coded message." },
    { word: "Decompose", definition: "To separate into constituent parts; rot." },
    { word: "Decorate", definition: "To make something more attractive." },
    { word: "Decorous", definition: "In keeping with good taste and propriety." },
    { word: "Decoy", definition: "Something used to lure or deceive." },
    { word: "Decree", definition: "An official order issued by authority." },
    { word: "Decry", definition: "To publicly denounce or criticize." },
    { word: "Dedicate", definition: "To devote time or effort to a purpose." },
    { word: "Deduce", definition: "To arrive at a conclusion by reasoning." },
    { word: "Deduct", definition: "To subtract or take away from a total." },
    { word: "Deed", definition: "An action performed intentionally or consciously." },
    { word: "Deem", definition: "To regard or consider in a specified way." },
    { word: "Deepen", definition: "To make or become deeper or more intense." },
    { word: "Default", definition: "Failure to fulfill an obligation." },
    { word: "Defeat", definition: "To win a victory over someone." },
    { word: "Defect", definition: "A shortcoming or imperfection." },
    { word: "Defend", definition: "To resist an attack made on someone." },
    { word: "Defer", definition: "To put off an action to a later time." },
    { word: "Deference", definition: "Humble submission and respect." },
    { word: "Defiant", definition: "Showing defiance; boldly resistant." },
    { word: "Deficiency", definition: "A lack or shortage of something." },
    { word: "Deficit", definition: "An amount that is less than needed." },

    // === E (Words 291-370) ===
    { word: "Eager", definition: "Strongly wanting to do something; enthusiastic." },
    { word: "Eagle", definition: "A large bird of prey with keen vision." },
    { word: "Earthen", definition: "Made of earth or baked clay." },
    { word: "Earthy", definition: "Realistic and practical; coarse." },
    { word: "Ease", definition: "Absence of difficulty or effort." },
    { word: "Ebb", definition: "To gradually decline or recede." },
    { word: "Ebullient", definition: "Cheerful and full of energy." },
    { word: "Eccentric", definition: "Unconventional and slightly strange." },
    { word: "Ecclesiastic", definition: "Relating to the Christian Church." },
    { word: "Eclipse", definition: "To surpass in importance; overshadow." },
    { word: "Eclectic", definition: "Deriving ideas from diverse sources." },
    { word: "Economy", definition: "Careful management of resources." },
    { word: "Ecstasy", definition: "An overwhelming feeling of happiness." },
    { word: "Ecstatic", definition: "Feeling overwhelming happiness." },
    { word: "Eddy", definition: "A circular movement of water or air." },
    { word: "Edible", definition: "Fit to be eaten as food." },
    { word: "Edict", definition: "An official order or proclamation." },
    { word: "Eerie", definition: "Strange and frightening." },
    { word: "Effect", definition: "A change produced by an action." },
    { word: "Effective", definition: "Successful in producing a desired result." },
    { word: "Effervescent", definition: "Vivacious and enthusiastic; bubbling." },
    { word: "Effete", definition: "Affected, over-refined, and ineffectual." },
    { word: "Efficacy", definition: "The ability to produce a desired result." },
    { word: "Efficient", definition: "Achieving maximum productivity with minimum effort." },
    { word: "Effigy", definition: "A sculpture or model of a person." },
    { word: "Effortless", definition: "Requiring no physical or mental exertion." },
    { word: "Egalitarian", definition: "Believing in equality for all people." },
    { word: "Ego", definition: "A person's sense of self-importance." },
    { word: "Egocentric", definition: "Thinking only of oneself; self-centered." },
    { word: "Egotism", definition: "Excessive conceit or self-absorption." },
    { word: "Egregious", definition: "Outstandingly bad; shocking." },
    { word: "Egress", definition: "A way out; exit." },
    { word: "Eight", definition: "The number after seven." },
    { word: "Elaborate", definition: "Involving many careful details." },
    { word: "Elapse", definition: "To pass or slip by time." },
    { word: "Elastic", definition: "Capable of returning to original shape." },
    { word: "Elate", definition: "To make someone ecstatically happy." },
    { word: "Elbow", definition: "The joint connecting the arm and forearm." },
    { word: "Elder", definition: "Older or of greater age." },
    { word: "Elderly", definition: "Old or aging." },
    { word: "Elect", definition: "To choose someone for public office." },
    { word: "Elegant", definition: "Graceful and stylish in appearance." },
    { word: "Elemental", definition: "Relating to the basic elements." },
    { word: "Elementary", definition: "Relating to basic principles; simple." },
    { word: "Elephant", definition: "A very large gray mammal with a trunk." },
    { word: "Elevate", definition: "To raise to a higher position." },
    { word: "Elevation", definition: "The height above a given level." },
    { word: "Elevator", definition: "A platform for raising and lowering people." },
    { word: "Eleven", definition: "The number after ten." },
    { word: "Eligible", definition: "Having the right to participate or be chosen." },
    { word: "Eliminate", definition: "To completely remove or get rid of." },
    { word: "Elite", definition: "A select group considered superior." },
    { word: "Eloquent", definition: "Fluent or persuasive in speaking or writing." },
    { word: "Elucidate", definition: "To make something clear; explain." },
    { word: "Elude", definition: "To escape from someone by cunning." },
    { word: "Elusive", definition: "Difficult to find or achieve." },
    { word: "Emaciated", definition: "Abnormally thin and weak." },
    { word: "Emanate", definition: "To originate from a source." },
    { word: "Emancipate", definition: "To set free from restraint or control." },
    { word: "Embellish", definition: "To make something more attractive by adding details." },
    { word: "Ember", definition: "A small piece of burning coal or wood." },
    { word: "Emblem", definition: "A symbol representing a particular idea." },
    { word: "Embody", definition: "To express an idea in tangible form." },
    { word: "Embrace", definition: "To accept or support willingly." },
    { word: "Embroider", definition: "To decorate with needlework." },
    { word: "Embroil", definition: "To involve in conflict or difficulties." },
    { word: "Embryo", definition: "An unborn offspring in development." },
    { word: "Emerald", definition: "A bright green precious gemstone." },
    { word: "Emergency", definition: "A serious situation requiring immediate action." },
    { word: "Emerge", definition: "To move out of or away from something." },
    { word: "Emergence", definition: "The process of coming into existence." },
    { word: "Emigrant", definition: "A person who leaves their country to settle elsewhere." },

    // === F (Words 371-450) ===
    { word: "Fabulous", definition: "Extraordinarily good; mythical." },
    { word: "Facade", definition: "The face of a building; false appearance." },
    { word: "Facet", definition: "One side of something many-sided." },
    { word: "Facetious", definition: "Treating serious issues with inappropriate humor." },
    { word: "Facile", definition: "Appearing neat and easy but lacking depth." },
    { word: "Facilitate", definition: "To make an action or process easier." },
    { word: "Facility", definition: "A place for a particular activity." },
    { word: "Facsimile", definition: "An exact copy or reproduction." },
    { word: "Fact", definition: "Something that is known to be true." },
    { word: "Faction", definition: "A small organized dissenting group." },
    { word: "Factious", definition: "Likely to cause disagreement." },
    { word: "Factitious", definition: "Artificially created; not natural." },
    { word: "Factotum", definition: "A person employed to do various jobs." },
    { word: "Factual", definition: "Concerned with what is actually true." },
    { word: "Faculties", definition: "Mental or physical powers." },
    { word: "Fade", definition: "To gradually disappear or lose color." },
    { word: "Fail", definition: "To be unsuccessful in achieving a goal." },
    { word: "Faint", definition: "Lacking clarity or brightness; weak." },
    { word: "Fair", definition: "Impartial and just; beautiful." },
    { word: "Fairy", definition: "A small imaginary being with magical powers." },
    { word: "Faith", definition: "Complete trust or confidence." },
    { word: "Faithful", definition: "Remaining loyal and steadfast." },
    { word: "Fake", definition: "Not genuine; counterfeit." },
    { word: "Falcon", definition: "A fast-flying bird of prey." },
    { word: "Fall", definition: "To move downward freely." },
    { word: "Fallacy", definition: "A mistaken belief based on unsound reasoning." },
    { word: "Fallible", definition: "Capable of making mistakes." },
    { word: "Fallow", definition: "Left unplanted for a period." },
    { word: "False", definition: "Not according with truth or fact." },
    { word: "Falter", definition: "To move unsteadily; hesitate." },
    { word: "Fame", definition: "The state of being widely known." },
    { word: "Familiar", definition: "Well-known from long association." },
    { word: "Family", definition: "A group of related people." },
    { word: "Famine", definition: "Extreme scarcity of food." },
    { word: "Famish", definition: "To suffer severely from hunger." },
    { word: "Famous", definition: "Known about by many people." },
    { word: "Fan", definition: "A device for creating a current of air." },
    { word: "Fanatic", definition: "A person with extreme enthusiasm." },
    { word: "Fancy", definition: "Elaborate in structure or decoration." },
    { word: "Fanfare", definition: "A short ceremonial trumpet flourish." },
    { word: "Fang", definition: "A long sharp tooth." },
    { word: "Fanning", definition: "The act of creating a current of air." },
    { word: "Fantasia", definition: "A musical composition in free form." },
    { word: "Fantastic", definition: "Extraordinarily good; imaginative." },
    { word: "Fantasy", definition: "The faculty of imagining impossible things." },
    { word: "Faraway", definition: "Distant in space or time." },
    { word: "Fare", definition: "The money paid for a journey." },
    { word: "Farewell", definition: "A goodbye or parting." },
    { word: "Farm", definition: "An area of land for cultivation." },
    { word: "Farther", definition: "At a greater distance." },
    { word: "Fascinate", definition: "To attract and hold the attention of." },
    { word: "Fascism", definition: "An authoritarian and nationalistic political system." },
    { word: "Fast", definition: "Moving or capable of moving quickly." },
    { word: "Fasten", definition: "To close or secure something." },
    { word: "Fastidious", definition: "Very attentive to detail; meticulous." },
    { word: "Fatal", definition: "Causing death; decisive." },
    { word: "Fate", definition: "The development of events beyond control." },
    { word: "Fated", definition: "Destined to happen." },
    { word: "Father", definition: "A male parent." },
    { word: "Fatigue", definition: "Extreme tiredness; exhaustion." },
    { word: "Fatten", definition: "To make someone or something fat." },
    { word: "Fault", definition: "An unattractive or unsatisfactory feature." },
    { word: "Faulty", definition: "Defective or imperfect." },
    { word: "Favor", definition: "An act of kindness beyond duty." },
    { word: "Favorite", definition: "Preferred before all others." },
    { word: "Fawn", definition: "A young deer; to flatter obsequiously." },
    { word: "Fear", definition: "An unpleasant emotion caused by danger." },
    { word: "Fearful", definition: "Feeling or showing fear." },
    { word: "Fearless", definition: "Lacking fear; brave." },
    { word: "Feasible", definition: "Possible to do easily or conveniently." },
    { word: "Feast", definition: "A large meal for celebration." },
    { word: "Feat", definition: "An achievement that requires great skill." },

    // === G (Words 451-520) ===
    { word: "Gabble", definition: "To talk rapidly and incoherently." },
    { word: "Gadfly", definition: "A person who annoys others by criticism." },
    { word: "Gaiety", definition: "The state of being cheerful; merriment." },
    { word: "Gain", definition: "To obtain or secure something." },
    { word: "Gainsay", definition: "To deny or contradict something." },
    { word: "Gait", definition: "A person's manner of walking." },
    { word: "Gala", definition: "A festive celebration or entertainment." },
    { word: "Galaxy", definition: "A system of millions of stars." },
    { word: "Gale", definition: "A very strong wind." },
    { word: "Gallop", definition: "The fastest pace of a horse." },
    { word: "Gallant", definition: "Brave; chivalrous; courteous to women." },
    { word: "Gallery", definition: "A room for displaying artworks." },
    { word: "Galvanize", definition: "To shock into action; stimulate." },
    { word: "Gambit", definition: "An opening move to gain advantage." },
    { word: "Gamble", definition: "To take risky action hoping for success." },
    { word: "Gambol", definition: "To run or jump about playfully." },
    { word: "Game", definition: "An activity for entertainment." },
    { word: "Gamma", definition: "The third letter of the Greek alphabet." },
    { word: "Gang", definition: "An organized group of criminals." },
    { word: "Gangster", definition: "A member of a gang of criminals." },
    { word: "Gap", definition: "A break or opening in something." },
    { word: "Gape", definition: "To stare with open mouth." },
    { word: "Garb", definition: "Clothing or dress of a distinctive style." },
    { word: "Garble", definition: "To confuse or distort." },
    { word: "Garden", definition: "A piece of ground for growing plants." },
    { word: "Gargantuan", definition: "Enormously large; gigantic." },
    { word: "Garish", definition: "Showy and tasteless in appearance." },
    { word: "Garland", definition: "A wreath of flowers or leaves." },
    { word: "Garment", definition: "An item of clothing." },
    { word: "Garnish", definition: "To decorate or embellish food." },
    { word: "Garner", definition: "To gather or collect something." },
    { word: "Garrison", definition: "A body of troops stationed in a fort." },
    { word: "Garrote", definition: "To strangle with a wire or cord." },
    { word: "Garrulous", definition: "Excessively talkative; wordy." },
    { word: "Gash", definition: "A long deep cut." },
    { word: "Gaslight", definition: "To manipulate someone into questioning reality." },
    { word: "Gasp", definition: "To catch breath in surprise." },
    { word: "Gastric", definition: "Relating to the stomach." },
    { word: "Gate", definition: "A hinged barrier for an opening." },
    { word: "Gather", definition: "To bring together in one place." },
    { word: "Gaudy", definition: "Tastelessly showy or colorful." },
    { word: "Gauge", definition: "To estimate or determine." },
    { word: "Gaussian", definition: "Relating to normal distribution in statistics." },
    { word: "Gaunt", definition: "Lean and haggard; grim and desolate." },
    { word: "Gauze", definition: "Thin translucent fabric or dressing." },
    { word: "Gavel", definition: "A small mallet for court proceedings." },
    { word: "Gawk", definition: "To stare openly and stupidly." },
    { word: "Gaze", definition: "To look steadily and intently." },
    { word: "Gear", definition: "Equipment or apparatus for a purpose." },
    { word: "Gel", definition: "A semi-solid substance; to solidify." },
    { word: "Gem", definition: "A precious stone; something valued." },
    { word: "Geminate", definition: "To arrange in pairs; double." },
    { word: "Gender", definition: "The state of being male or female." },
    { word: "Gene", definition: "A unit of heredity in living organisms." },
    { word: "General", definition: "Affecting or relating to all." },
    { word: "Generate", definition: "To produce or create something." },
    { word: "Generosity", definition: "The quality of being kind and generous." },
    { word: "Generous", definition: "Showing readiness to give more than necessary." },
    { word: "Genesis", definition: "The origin or formation of something." },
    { word: "Genetic", definition: "Relating to genes or heredity." },
    { word: "Genial", definition: "Friendly and cheerful." },
    { word: "Genius", definition: "Exceptional intellectual or creative power." },
    { word: "Genre", definition: "A category of artistic composition." },
    { word: "Gentile", definition: "A person who is not Jewish." },
    { word: "Gentle", definition: "Mild in manner or temperament." },
    { word: "Genuine", definition: "Truly what it is said to be; authentic." },
    { word: "Geology", definition: "The study of Earth's physical structure." },
    { word: "Geometric", definition: "Relating to geometry or geometric shapes." },
    { word: "Geometry", definition: "The branch of mathematics studying shapes." },
    { word: "Geriatric", definition: "Relating to elderly people." },

    // === H (Words 521-600) ===
    { word: "Habit", definition: "A settled tendency or usual manner." },
    { word: "Habitual", definition: "Done constantly as a habit." },
    { word: "Hack", definition: "To cut with rough blows." },
    { word: "Hackneyed", definition: "Lacking originality; overused." },
    { word: "Haggard", definition: "Looking exhausted and unwell." },
    { word: "Haggle", definition: "To dispute about a price." },
    { word: "Hail", definition: "Pellets of frozen rain; to acclaim." },
    { word: "Hallow", definition: "To make holy; consecrate." },
    { word: "Hallucination", definition: "An experience of something not present." },
    { word: "Halting", definition: "Slow and hesitant; stopping frequently." },
    { word: "Hamper", definition: "To hinder or impede movement." },
    { word: "Handicap", definition: "A disadvantage that makes achievement difficult." },
    { word: "Handle", definition: "To manage or deal with something." },
    { word: "Handsome", definition: "Good-looking; generous in amount." },
    { word: "Handy", definition: "Convenient; skillful with hands." },
    { word: "Haphazard", definition: "Lacking order or planning; random." },
    { word: "Hapless", definition: "Unfortunate; luckless." },
    { word: "Happen", definition: "To take place; occur." },
    { word: "Harangue", definition: "A lengthy and aggressive speech." },
    { word: "Harass", definition: "To subject to aggressive pressure." },
    { word: "Harbor", definition: "A sheltered port for ships." },
    { word: "Hard", definition: "Solid and firm to touch; difficult." },
    { word: "Hardy", definition: "Robust; capable of enduring hardship." },
    { word: "Hare", definition: "A fast-running animal like a rabbit." },
    { word: "Harm", definition: "Physical injury or damage." },
    { word: "Harmony", definition: "Agreement or concord; musical combination." },
    { word: "Harness", definition: "To utilize something for a purpose." },
    { word: "Harp", definition: "To talk persistently about something." },
    { word: "Harsh", definition: "Unpleasantly rough or severe." },
    { word: "Harvest", definition: "To gather a crop when ripe." },
    { word: "Haste", definition: "Excessive speed; urgency." },
    { word: "Hasty", definition: "Done or acting with excessive speed." },
    { word: "Hatch", definition: "To emerge from an egg." },
    { word: "Hate", definition: "Intense or passionate dislike." },
    { word: "Haughty", definition: "Arrogantly superior; disdainful." },
    { word: "Haunt", definition: "To appear as a ghost; to visit often." },
    { word: "Haven", definition: "A place of safety or refuge." },
    { word: "Havoc", definition: "Great destruction or devastation." },
    { word: "Hawk", definition: "A bird of prey; to sell goods aggressively." },
    { word: "Hazard", definition: "A danger or risk." },
    { word: "Hazardous", definition: "Risky or dangerous." },
    { word: "Haze", definition: "A slight obscuration of the air." },
    { word: "Headlong", definition: "In a reckless or hurried manner." },
    { word: "Headstrong", definition: "Determined to have one's own way." },
    { word: "Heal", definition: "To make healthy again; cure." },
    { word: "Health", definition: "The state of being free from illness." },
    { word: "Healthy", definition: "In good health; promoting health." },
    { word: "Heap", definition: "An untidy pile of something." },
    { word: "Hear", definition: "To perceive with the ear." },
    { word: "Hearken", definition: "To listen; give heed to." },
    { word: "Heart", definition: "The organ that pumps blood; center of emotion." },
    { word: "Hearty", definition: "Warm and friendly; vigorous." },
    { word: "Heave", definition: "To lift with great effort." },
    { word: "Heaven", definition: "The abode of God and the angels." },
    { word: "Heavy", definition: "Of great weight; difficult to lift." },
    { word: "Hebetude", definition: "Dullness or lethargy." },
    { word: "Heckle", definition: "To interrupt a speaker with comments." },
    { word: "Hedge", definition: "To limit or qualify something." },
    { word: "Hedonist", definition: "One who pursues pleasure as a goal." },
    { word: "Heed", definition: "To pay attention to; take notice." },
    { word: "Hefty", definition: "Large and strong; substantial." },
    { word: "Heinous", definition: "Hateful; wicked; atrocious." },
    { word: "Heir", definition: "A person legally entitled to property." },
    { word: "Herald", definition: "To announce or signal the approach of." },
    { word: "Herb", definition: "A plant used for flavoring or medicine." },
    { word: "Herbal", definition: "Relating to herbs." },
    { word: "Hereditary", definition: "Determined by genetic factors." },
    { word: "Heritage", definition: "Property inherited from past generations." },
    { word: "Hermaphrodite", definition: "Having both male and female organs." },
    { word: "Hermetic", definition: "Sealed airtight; impervious to external influence." },
    { word: "Hesitant", definition: "Tentative, unsure, or slow in acting." },
    { word: "Hesitate", definition: "To pause before saying or doing something." },
    { word: "Heterodox", definition: "Not conforming to accepted beliefs." },
    { word: "Heterogeneous", definition: "Diverse in character or content." },
    { word: "Heyday", definition: "The period of greatest prosperity." },

    // === I (Words 601-685) ===
    { word: "Iambic", definition: "Relating to a metrical foot of two syllables." },
    { word: "Ibidem", definition: "In the same place (used in citations)." },
    { word: "Iceberg", definition: "A large floating mass of ice." },
    { word: "Icicle", definition: "A hanging spike of ice formed by dripping water." },
    { word: "Icon", definition: "A symbol representing an object or idea." },
    { word: "Iconoclast", definition: "A person who attacks cherished beliefs." },
    { word: "Ideal", definition: "Satisfying one's conception of perfection." },
    { word: "Idealism", definition: "The practice of forming ideals; unrealistic." },
    { word: "Ideally", definition: "Preferably; in an ideal world." },
    { word: "Identical", definition: "Exactly the same." },
    { word: "Identification", definition: "The process of recognizing someone or something." },
    { word: "Identify", definition: "To establish the identity of." },
    { word: "Identity", definition: "The fact of being who or what a person is." },
    { word: "Ideology", definition: "A system of ideas and ideals." },
    { word: "Idiom", definition: "An expression with a meaning not deducible from words." },
    { word: "Idiosyncrasy", definition: "A distinctive or peculiar behavior." },
    { word: "Idle", definition: "Avoiding work; lazy; purposeless." },
    { word: "Idol", definition: "An image worshipped as a god." },
    { word: "Idolatry", definition: "Worship of idols; excessive admiration." },
    { word: "Idyllic", definition: "Extremely happy, peaceful, or picturesque." },
    { word: "Igloo", definition: "A dome-shaped Inuit house of ice blocks." },
    { word: "Ignoble", definition: "Not honorable in character; dishonorable." },
    { word: "Ignominious", definition: "Deserving public disgrace or shame." },
    { word: "Ignorance", definition: "Lack of knowledge or information." },
    { word: "Ignorant", definition: "Lacking knowledge or awareness." },
    { word: "Ignore", definition: "To refuse to take notice of." },
    { word: "Ilk", definition: "A type of person or thing similar to another." },
    { word: "Illegal", definition: "Contrary to or forbidden by law." },
    { word: "Illegible", definition: "Not clear enough to be read." },
    { word: "Illegitimate", definition: "Not authorized by law; born of unmarried parents." },
    { word: "Illiteracy", definition: "The inability to read or write." },
    { word: "Illiterate", definition: "Unable to read or write." },
    { word: "Illness", definition: "A disease or period of sickness." },
    { word: "Illogical", definition: "Lacking sense or clear reasoning." },
    { word: "Illusion", definition: "A false idea or belief; a deceptive appearance." },
    { word: "Illustrious", definition: "Well-known and admired for past achievements." },
    { word: "Image", definition: "A representation of the external form." },
    { word: "Imagery", definition: "Visually descriptive language." },
    { word: "Imaginable", definition: "Possible to think of; conceivable." },
    { word: "Imaginary", definition: "Existing only in imagination." },
    { word: "Imagination", definition: "The faculty of forming new ideas." },
    { word: "Imaginative", definition: "Having a lively imagination; original." },
    { word: "Imagine", definition: "To form a mental image of something." },
    { word: "Imbecile", definition: "A stupid or foolish person." },
    { word: "Imbibe", definition: "To absorb or assimilate ideas; to drink." },
    { word: "Imbue", definition: "To inspire or permeate with a feeling." },
    { word: "Imitate", definition: "To copy someone or something." },
    { word: "Imitation", definition: "The action of copying someone or something." },
    { word: "Immaculate", definition: "Perfectly clean or tidy; faultless." },
    { word: "Immature", definition: "Not fully developed; childish." },
    { word: "Imminent", definition: "About to happen; impending." },
    { word: "Immoral", definition: "Not conforming to accepted standards of morality." },
    { word: "Immortal", definition: "Living forever; never dying." },
    { word: "Immune", definition: "Resistant to a particular infection." },
    { word: "Immunity", definition: "The ability to resist a particular disease." },
    { word: "Immunize", definition: "To make someone immune to infection." },
    { word: "Immaterial", definition: "Unimportant; irrelevant." },
    { word: "Immature", definition: "Not fully developed; not mature." },
    { word: "Immemorial", definition: "Extending back beyond memory." },
    { word: "Immense", definition: "Extremely large; huge." },
    { word: "Immerse", definition: "To involve oneself deeply in something." },
    { word: "Immigrant", definition: "A person who comes to a country to settle." },
    { word: "Immigrate", definition: "To come to a country to live permanently." },
    { word: "Imminent", definition: "About to occur; impending." },
    { word: "Immobilize", definition: "To prevent something from moving." },
    { word: "Immoral", definition: "Not conforming to moral standards." },
    { word: "Immortal", definition: "Living forever; enduring eternally." },
    { word: "Immune", definition: "Protected from a disease; exempt." },
    { word: "Immutable", definition: "Unchanging over time; permanent." },
    { word: "Imp", definition: "A small mischievous devil or sprite." },
    { word: "Impact", definition: "The effect or influence of one thing on another." },
    { word: "Impair", definition: "To weaken or damage something." },
    { word: "Impale", definition: "To pierce with a sharp instrument." },
    { word: "Impalpable", definition: "Unable to be felt by touch." },
    { word: "Impartial", definition: "Treating all rivals or sides equally." },
    { word: "Impassable", definition: "Impossible to travel through." },
    { word: "Impasse", definition: "A deadlock with no escape." },

    // === J (Words 686-720) ===
    { word: "Jabber", definition: "To talk rapidly and excitedly but incoherently." },
    { word: "Jackanapes", definition: "A conceited or impudent person." },
    { word: "Jaded", definition: "Tired, bored, or lacking enthusiasm." },
    { word: "Jagged", definition: "Having a rough, uneven edge or surface." },
    { word: "Jail", definition: "A place for confinement of prisoners." },
    { word: "Jangle", definition: "To make a harsh metallic sound." },
    { word: "Janitor", definition: "A person employed to care for a building." },
    { word: "Jargon", definition: "Specialized terminology used by a group." },
    { word: "Jaundice", definition: "A medical condition causing yellowing of skin." },
    { word: "Jaunt", definition: "A short trip for pleasure." },
    { word: "Jaunty", definition: "Having a cheerful and carefree manner." },
    { word: "Jaw", definition: "The movable part of the mouth for chewing." },
    { word: "Jazz", definition: "A type of music of American origin." },
    { word: "Jealous", definition: "Feeling resentment against a rival." },
    { word: "Jealousy", definition: "The state of being jealous." },
    { word: "Jeer", definition: "To make rude and mocking remarks." },
    { word: "Jelly", definition: "A soft food made from fruit juice and gelatin." },
    { word: "Jeopardize", definition: "To put something at risk of harm." },
    { word: "Jeopardy", definition: "Danger of loss or harm." },
    { word: "Jerk", definition: "A quick sharp pull; a foolish person." },
    { word: "Jerky", definition: "Characterized by sudden stops and starts." },
    { word: "Jest", definition: "A thing said for amusement; a joke." },
    { word: "Jet", definition: "A rapid stream of liquid; an aircraft." },
    { word: "Jettison", definition: "To throw or drop something from a ship." },
    { word: "Jetty", definition: "A landing pier for ships." },
    { word: "Jewel", definition: "A precious stone; a valuable thing." },
    { word: "Jibe", definition: "To be in accord; to taunt." },
    { word: "Jig", definition: "A quick lively dance; a device for holding work." },
    { word: "Jigsaw", definition: "A puzzle cut into various shapes." },
    { word: "Jilt", definition: "To reject someone after a close relationship." },
    { word: "Jingle", definition: "A light ringing sound; a short tune for advertising." },
    { word: "Jinx", definition: "A person or thing that brings bad luck." },
    { word: "Jitters", definition: "Feelings of extreme nervousness." },
    { word: "Jittery", definition: "Nervous and unable to relax." },
    { word: "Job", definition: "A paid position of regular employment." },
    { word: "Jockey", definition: "A person who rides horses in races." },
    { word: "Jog", definition: "To run at a slow, steady pace." },
    { word: "Join", definition: "To connect or combine together." },
    { word: "Joint", definition: "A point where two things are joined." },
    { word: "Joke", definition: "Something said to cause amusement." },
    { word: "Jolly", definition: "Happy and cheerful." },
    { word: "Jolt", definition: "To push or shake abruptly." },
    { word: "Jot", definition: "To write something quickly." },
    { word: "Journal", definition: "A daily record of news or events." },
    { word: "Journey", definition: "An act of traveling from one place to another." },
    { word: "Jovial", definition: "Cheerful and friendly." },
    { word: "Joy", definition: "A feeling of great pleasure and happiness." },
    { word: "Joyful", definition: "Feeling or expressing great happiness." },
    { word: "Joyous", definition: "Full of happiness and joy." },
    { word: "Jubilation", definition: "A feeling of great happiness and triumph." },
    { word: "Jubilant", definition: "Feeling or expressing great happiness." },
    { word: "Judicial", definition: "Relating to the administration of justice." },
    { word: "Judicious", definition: "Having good judgment; wise." },
    { word: "Juggle", definition: "To toss objects continuously." },
    { word: "Juice", definition: "Liquid from fruits or vegetables." },
    { word: "Juicy", definition: "Containing much juice; interesting or sensational." },
    { word: "Jumble", definition: "An untidy collection of things." },
    { word: "Jump", definition: "To push off the ground with feet." },
    { word: "Junction", definition: "A point where two things join." },
    { word: "Juncture", definition: "A particular point in time or events." },
    { word: "Jungle", definition: "An area of dense forest in tropical regions." },
    { word: "Junior", definition: "Lower in rank or standing." },
    { word: "Junk", definition: "Discarded articles considered useless." },
    { word: "Junket", definition: "A trip made for pleasure at public expense." },
    { word: "Jury", definition: "A body of people sworn to give a verdict." },
    { word: "Just", definition: "Based on fairness; right." },
    { word: "Justice", definition: "The quality of being fair and reasonable." },
    { word: "Justifiable", definition: "Able to be shown to be right or reasonable." },
    { word: "Justify", definition: "To prove to be right or reasonable." },
    { word: "Justly", definition: "In a fair and right manner." },
    { word: "Juvenile", definition: "Relating to young people; childish." },

    // === K (Words 721-745) ===
    { word: "Keel", definition: "The longitudinal structure along a ship's bottom." },
    { word: "Keen", definition: "Having a sharp edge; enthusiastic." },
    { word: "Keep", definition: "To have or retain possession of." },
    { word: "Ken", definition: "The range of knowledge or sight." },
    { word: "Kennel", definition: "A shelter for a dog or dogs." },
    { word: "Kernel", definition: "A softer part inside a hard shell." },
    { word: "Kettle", definition: "A container for boiling water." },
    { word: "Key", definition: "A small metal instrument for opening a lock." },
    { word: "Keyboard", definition: "A panel of keys for operating a computer." },
    { word: "Kick", definition: "To strike with the foot." },
    { word: "Kid", definition: "A child; a young goat." },
    { word: "Kidnap", definition: "To abduct someone and hold them captive." },
    { word: "Kidney", definition: "An organ that filters blood." },
    { word: "Kill", definition: "To cause the death of a living thing." },
    { word: "Killer", definition: "A person who kills; something very difficult." },
    { word: "Kind", definition: "A group with similar characteristics; gentle." },
    { word: "Kindle", definition: "To light or set on fire; arouse feelings." },
    { word: "Kindred", definition: "Related; similar in nature." },
    { word: "Kinetic", definition: "Relating to or resulting from motion." },
    { word: "King", definition: "A male ruler of an independent state." },
    { word: "Kingdom", definition: "A country ruled by a king or queen." },
    { word: "Kismet", definition: "Destiny; fate." },
    { word: "Kiss", definition: "To touch with lips as a sign of affection." },
    { word: "Kit", definition: "A set of articles or equipment." },
    { word: "Kitchen", definition: "A room where food is prepared and cooked." },
    { word: "Kite", definition: "A light frame covered with paper for flying." },
    { word: "Kitten", definition: "A young cat." },
    { word: "Knack", definition: "A special talent or skill." },
    { word: "Knave", definition: "A dishonest or unscrupulous man." },
    { word: "Knead", definition: "To work dough with hands." },
    { word: "Knee", definition: "The joint between the thigh and lower leg." },
    { word: "Kneel", definition: "To go down on one's knees." },
    { word: "Knell", definition: "The sound of a bell, especially for a death." },
    { word: "Knife", definition: "An instrument for cutting." },
    { word: "Knight", definition: "A mounted soldier in armor." },
    { word: "Knit", definition: "To make fabric by interlocking loops of yarn." },
    { word: "Knob", definition: "A rounded handle or control." },
    { word: "Knock", definition: "To strike a surface with a sharp blow." },
    { word: "Knoll", definition: "A small hill or mound." },
    { word: "Knot", definition: "A fastening made by tying rope." },
    { word: "Know", definition: "To be aware of through observation or inquiry." },
    { word: "Knowledge", definition: "Information and skills acquired through experience." },
    { word: "Known", definition: "Recognized or identified by many." },
    { word: "Kudos", definition: "Praise and honor received for achievement." },

    // === L (Words 746-820) ===
    { word: "Label", definition: "A small piece of paper with information." },
    { word: "Labor", definition: "Work, especially physical work." },
    { word: "Laborious", definition: "Requiring considerable time and effort." },
    { word: "Labour", definition: "Work, especially hard physical work." },
    { word: "Labyrinth", definition: "A complicated network of passages." },
    { word: "Lace", definition: "A fine open fabric of cotton or silk." },
    { word: "Lack", definition: "The state of being without something." },
    { word: "Lackluster", definition: "Lacking distinctive qualities; dull." },
    { word: "Laconic", definition: "Using very few words; concise." },
    { word: "Laden", definition: "Heavily loaded or weighted down." },
    { word: "Lad", definition: "A boy or young man." },
    { word: "Lady", definition: "A woman of refined manners." },
    { word: "Lag", definition: "To fall behind in movement or progress." },
    { word: "Lagoon", definition: "A stretch of salt water separated from the sea." },
    { word: "Lair", definition: "A place where a wild animal rests." },
    { word: "Lake", definition: "A large body of water surrounded by land." },
    { word: "Lamb", definition: "A young sheep." },
    { word: "Lame", definition: "Unable to walk properly; weak or unconvincing." },
    { word: "Lament", definition: "To express grief or sorrow." },
    { word: "Lamentable", definition: "Regrettably unsatisfactory; deplorable." },
    { word: "Lamp", definition: "A device for giving light." },
    { word: "Lance", definition: "A long weapon used by horsemen." },
    { word: "Land", definition: "The solid part of Earth's surface." },
    { word: "Landmark", definition: "A conspicuous object on land marking a boundary." },
    { word: "Landscape", definition: "The visible features of an area of land." },
    { word: "Lane", definition: "A narrow road or path." },
    { word: "Languid", definition: "Displaying sluggishness; slow and relaxed." },
    { word: "Languish", definition: "To grow weak or feeble." },
    { word: "Languor", definition: "The state of feeling pleasantly tired." },
    { word: "Lanky", definition: "Ungracefully tall and thin." },
    { word: "Lantern", definition: "A lamp with a transparent case." },
    { word: "Lap", definition: "The flat area between the waist and knees." },
    { word: "Lapse", definition: "A temporary failure of concentration or judgment." },
    { word: "Larceny", definition: "Theft of personal property." },
    { word: "Large", definition: "Of considerable size or extent." },
    { word: "Largess", definition: "Generosity in giving money or gifts." },
    { word: "Lark", definition: "A small songbird; a carefree adventure." },
    { word: "Larva", definition: "The active immature form of an insect." },
    { word: "Larynx", definition: "The hollow muscular organ containing vocal cords." },
    { word: "Lascivious", definition: "Showing excessive sexual desire; lewd." },
    { word: "Lash", definition: "To strike with a whip or similar." },
    { word: "Lass", definition: "A girl or young woman." },
    { word: "Lassitude", definition: "A state of weariness or listlessness." },
    { word: "Last", definition: "Coming after all others in time or order." },
    { word: "Latch", definition: "A metal bar for fastening a door." },
    { word: "Late", definition: "Coming after the expected time." },
    { word: "Latent", definition: "Existing but not yet developed or visible." },
    { word: "Lateral", definition: "Relating to the side; sideways." },
    { word: "Latitude", definition: "Angular distance north or south of the equator." },
    { word: "Latter", definition: "Nearer to the end; the second of two." },
    { word: "Laud", definition: "To praise; extol." },
    { word: "Laudable", definition: "Deserving praise and commendation." },
    { word: "Laugh", definition: "To make sounds expressing amusement." },
    { word: "Launch", definition: "To set a boat or ship in motion." },
    { word: "Laundry", definition: "Clothes or linens to be washed." },
    { word: "Launder", definition: "To wash clothes; to process illegally obtained money." },
    { word: "Laurel", definition: "An evergreen shrub used as a symbol of victory." },
    { word: "Lava", definition: "Molten rock from a volcano." },
    { word: "Lavish", definition: "Extravagant; giving generously." },
    { word: "Law", definition: "The system of rules recognized by a country." },
    { word: "Lawn", definition: "An area of mown grass." },
    { word: "Lawyer", definition: "A person who practices law." },
    { word: "Lax", definition: "Not strict or severe; careless." },
    { word: "Laxity", definition: "Lack of strictness or care." },
    { word: "Lay", definition: "To put something down." },
    { word: "Layer", definition: "A sheet or thickness of material." },
    { word: "Layman", definition: "A person without professional knowledge." },
    { word: "Layout", definition: "The way in which something is arranged." },
    { word: "Lazy", definition: "Unwilling to work or use energy." },
    { word: "Lead", definition: "To show the way; a heavy metal." },
    { word: "Leader", definition: "The person who leads a group." },
    { word: "Leaf", definition: "A flattened structure of a plant." },

    // === M (Words 821-895) ===
    { word: "Mace", definition: "A ceremonial staff; a spice from nutmeg." },
    { word: "Machine", definition: "A device with moving parts performing a task." },
    { word: "Mad", definition: "Insane; extremely angry; very enthusiastic." },
    { word: "Madden", definition: "To make someone very angry or annoyed." },
    { word: "Madness", definition: "The state of being mentally ill; great folly." },
    { word: "Maelstrom", definition: "A powerful whirlpool; a situation of confusion." },
    { word: "Magenta", definition: "A purplish-red color." },
    { word: "Magic", definition: "The power of influencing events by supernatural means." },
    { word: "Magical", definition: "Relating to magic; beautiful or delightful." },
    { word: "Magistrate", definition: "A civil officer administering the law." },
    { word: "Magnetic", definition: "Having the property of magnetism; attractive." },
    { word: "Magnificent", definition: "Impressively beautiful or grand." },
    { word: "Magnify", definition: "To make something appear larger." },
    { word: "Magnitude", definition: "The great size or extent of something." },
    { word: "Mahogany", definition: "A tropical hardwood tree; reddish-brown color." },
    { word: "Maid", definition: "A female domestic servant." },
    { word: "Maiden", definition: "An unmarried girl or young woman." },
    { word: "Mail", definition: "Letters and parcels sent by post." },
    { word: "Main", definition: "Most important; principal." },
    { word: "Maintain", definition: "To keep something in good condition." },
    { word: "Maintenance", definition: "The process of maintaining something." },
    { word: "Maize", definition: "A cereal plant also known as corn." },
    { word: "Majestic", definition: "Having impressive beauty or dignity." },
    { word: "Majesty", definition: "Impressive dignity; royal authority." },
    { word: "Major", definition: "Important or significant; a military rank." },
    { word: "Make", definition: "To create or construct something." },
    { word: "Makeup", definition: "Cosmetics applied to the face." },
    { word: "Malady", definition: "A disease or ailment." },
    { word: "Malaise", definition: "A general feeling of discomfort or illness." },
    { word: "Malaria", definition: "A disease transmitted by mosquitoes." },
    { word: "Male", definition: "Relating to the sex that produces sperm." },
    { word: "Malevolent", definition: "Having or showing evil intentions." },
    { word: "Malice", definition: "The intention to do evil or cause harm." },
    { word: "Malicious", definition: "Characterized by malice; intending harm." },
    { word: "Malign", definition: "To speak about someone in a harmful manner." },
    { word: "Malignant", definition: "Evil in nature; likely to cause harm." },
    { word: "Malleable", definition: "Able to be shaped; easily influenced." },
    { word: "Mallet", definition: "A hammer with a large wooden head." },
    { word: "Malnutrition", definition: "Lack of proper nutrition." },
    { word: "Maltreat", definition: "To treat someone cruelly or badly." },
    { word: "Mammal", definition: "A warm-blooded animal with hair and mammary glands." },
    { word: "Man", definition: "An adult male human." },
    { word: "Manage", definition: "To succeed in doing something; to direct." },
    { word: "Management", definition: "The process of managing something." },
    { word: "Manager", definition: "A person responsible for controlling something." },
    { word: "Mandate", definition: "An official order to do something." },
    { word: "Mandatory", definition: "Required by law; compulsory." },
    { word: "Maneuver", definition: "A planned movement; to move skillfully." },
    { word: "Manifest", definition: "Clear or obvious to the eye or mind." },
    { word: "Manifestation", definition: "An outward sign of something." },
    { word: "Manipulate", definition: "To control or influence cleverly." },
    { word: "Manner", definition: "A way of doing something; social behavior." },
    { word: "Manor", definition: "A large country house with lands." },
    { word: "Mansion", definition: "A large impressive house." },
    { word: "Mantel", definition: "A shelf above a fireplace." },
    { word: "Manual", definition: "Relating to using hands; a handbook." },
    { word: "Manufacture", definition: "To make something on a large scale." },
    { word: "Manuscript", definition: "A handwritten or typed document." },
    { word: "Many", definition: "A large number of." },
    { word: "Map", definition: "A diagram of an area of land." },
    { word: "Mar", definition: "To spoil or damage something." },
    { word: "Marathon", definition: "A long-distance running race." },
    { word: "Marble", definition: "A hard crystalline rock used in sculpture." },
    { word: "March", definition: "To walk in a military manner; the third month." },
    { word: "Margin", definition: "The edge or border of something." },
    { word: "Marginal", definition: "Of minor importance; at the edge." },
    { word: "Marina", definition: "A harbor for small boats." },
    { word: "Marine", definition: "Relating to the sea; a soldier at sea." },
    { word: "Marital", definition: "Relating to marriage." },
    { word: "Maritime", definition: "Connected with the sea or navigation." },
    { word: "Mark", definition: "A visible impression on a surface." },
    { word: "Market", definition: "A place where goods are sold." },
    { word: "Marmalade", definition: "A preserve made from citrus fruits." },
    { word: "Marriage", definition: "The legal union of two people." },

    // === N (Words 896-950) ===
    { word: "Nadir", definition: "The lowest point in the fortunes of a person." },
    { word: "Naive", definition: "Showing a lack of experience or sophistication." },
    { word: "Naked", definition: "Not covered by clothing; exposed." },
    { word: "Name", definition: "A word by which a person or thing is known." },
    { word: "Nameless", definition: "Having no name; anonymous." },
    { word: "Nanny", definition: "A person employed to care for children." },
    { word: "Nap", definition: "A short sleep." },
    { word: "Nape", definition: "The back of the neck." },
    { word: "Napkin", definition: "A square piece of cloth for wiping the mouth." },
    { word: "Narcissism", definition: "Excessive interest in oneself." },
    { word: "Narrate", definition: "To tell a story or describe events." },
    { word: "Narrative", definition: "A spoken or written account of events." },
    { word: "Narrator", definition: "A person who narrates a story." },
    { word: "Narrow", definition: "Of small width; limited in extent." },
    { word: "Nasty", definition: "Unpleasant or offensive; spiteful." },
    { word: "Nation", definition: "A large body of people with shared culture." },
    { word: "National", definition: "Relating to a nation; a citizen." },
    { word: "Native", definition: "Associated with a place from birth." },
    { word: "Natural", definition: "Existing in nature; not artificial." },
    { word: "Nature", definition: "The physical world and living things." },
    { word: "Naughty", definition: "Badly behaved; disobedient." },
    { word: "Nautical", definition: "Relating to ships or sailing." },
    { word: "Naval", definition: "Relating to a navy or warships." },
    { word: "Navigate", definition: "To plan and direct a route." },
    { word: "Navy", definition: "A nation's warships and personnel." },
    { word: "Near", definition: "Close to in distance or time." },
    { word: "Nearby", definition: "Close at hand; not far away." },
    { word: "Neat", definition: "Arranged in a tidy way; simple and clever." },
    { word: "Necessary", definition: "Required to achieve a result; essential." },
    { word: "Necessity", definition: "The fact of being required; indispensable thing." },
    { word: "Neck", definition: "The part connecting head and body." },
    { word: "Necklace", definition: "An ornament worn around the neck." },
    { word: "Nectar", definition: "A sugary fluid produced by flowers." },
    { word: "Need", definition: "To require something; necessity." },
    { word: "Needle", definition: "A thin pointed metal implement for sewing." },
    { word: "Needless", definition: "Unnecessary; avoidable." },
    { word: "Needy", definition: "Lacking basic necessities; poor." },
    { word: "Negative", definition: "Consisting of the absence of positive qualities." },
    { word: "Neglect", definition: "To fail to care for properly." },
    { word: "Negligence", definition: "Failure to take proper care." },
    { word: "Negligent", definition: "Failing to take proper care." },
    { word: "Negligible", definition: "So small as to be unimportant." },
    { word: "Negotiate", definition: "To discuss to reach an agreement." },
    { word: "Negotiation", definition: "Discussion aimed at reaching an agreement." },
    { word: "Neighbor", definition: "A person living next door or nearby." },
    { word: "Neighborhood", definition: "A district or community within a town." },
    { word: "Neither", definition: "Not one nor the other." },
    { word: "Nemesis", definition: "An opponent who cannot be beaten." },
    { word: "Neon", definition: "A colorless gas used in lights." },
    { word: "Nerve", definition: "A fiber transmitting impulses; boldness." },
    { word: "Nervous", definition: "Easily agitated; anxious." },
    { word: "Nest", definition: "A structure built by birds for laying eggs." },
    { word: "Nestle", definition: "To settle comfortably and warmly." },
    { word: "Net", definition: "A fabric of spaced threads; remaining after deductions." },

    // === O (Words 951-985) ===
    { word: "Oasis", definition: "A fertile spot in a desert." },
    { word: "Oath", definition: "A solemn promise; a profane word." },
    { word: "Obedience", definition: "Compliance with orders or requests." },
    { word: "Obedient", definition: "Complying with orders or requests." },
    { word: "Obey", definition: "To comply with orders or requests." },
    { word: "Obese", definition: "Very fat or overweight." },
    { word: "Obesity", definition: "The condition of being very overweight." },
    { word: "Obey", definition: "To comply with the wishes of someone." },
    { word: "Object", definition: "A material thing; to oppose or disagree." },
    { word: "Objection", definition: "An expression of opposition or disapproval." },
    { word: "Objective", definition: "Not influenced by personal feelings; a goal." },
    { word: "Obligation", definition: "A duty or commitment." },
    { word: "Oblige", definition: "To require or bind by legal or moral duty." },
    { word: "Obliging", definition: "Willing to help; accommodating." },
    { word: "Oblivion", definition: "The state of being unknown or forgotten." },
    { word: "Oblivious", definition: "Not aware of what is happening." },
    { word: "Obscure", definition: "Not discovered or known; unclear." },
    { word: "Observation", definition: "The action of noticing something." },
    { word: "Observe", definition: "To notice or watch carefully." },
    { word: "Obsess", definition: "To preoccupy the mind constantly." },
    { word: "Obsession", definition: "An idea that preoccupies the mind." },
    { word: "Obsessive", definition: "Characterized by obsession." },
    { word: "Obstacle", definition: "Something that blocks progress." },
    { word: "Obstinate", definition: "Stubbornly refusing to change." },
    { word: "Obstruct", definition: "To block or impede progress." },
    { word: "Obstruction", definition: "Something that blocks a passage." },
    { word: "Obtain", definition: "To get or acquire something." },
    { word: "Obvious", definition: "Easily perceived or understood." },
    { word: "Occasion", definition: "A particular time or event." },
    { word: "Occasional", definition: "Happening infrequently." },
    { word: "Occult", definition: "Supernatural or magical practices." },
    { word: "Occupy", definition: "To take possession of or fill." },
    { word: "Occur", definition: "To happen or take place." },
    { word: "Occurrence", definition: "An event or incident." },
    { word: "Ocean", definition: "A very large body of salt water." },
    { word: "Odd", definition: "Strange; not even-numbered." },
    { word: "Odor", definition: "A distinctive smell." },
    { word: "Odorous", definition: "Having a distinctive smell." },
    { word: "Offend", definition: "To cause resentment or annoyance." },
    { word: "Offense", definition: "A breach of law; an attack." },
    { word: "Offensive", definition: "Causing anger or upset; attacking." },
    { word: "Offer", definition: "To present something for acceptance." },
    { word: "Office", definition: "A place where business is conducted." },
    { word: "Officer", definition: "A person holding a position of authority." },
    { word: "Official", definition: "Relating to authority; a person in office." },
    { word: "Offset", definition: "To counterbalance or compensate for." },
    { word: "Offspring", definition: "A person's child or children." },
    { word: "Omen", definition: "A sign of something to come." },
    { word: "Ominous", definition: "Giving the impression of something bad." },
    { word: "Omit", definition: "To leave out or exclude." },
    { word: "Omission", definition: "The act of leaving something out." },
    { word: "Omnipotent", definition: "Having unlimited power; all-powerful." },
    { word: "Omnipresent", definition: "Widely or constantly encountered." },
    { word: "Omniscient", definition: "Knowing everything; all-knowing." },
    { word: "Onerous", definition: "Involving heavy obligations; burdensome." },
    { word: "Onset", definition: "The beginning of something unpleasant." },
    { word: "Onslaught", definition: "A fierce or destructive attack." },
    { word: "Onto", definition: "Moving to a location on something." },
    { word: "Onward", definition: "Moving forward; advancing." },
    { word: "Ooze", definition: "To slowly trickle or seep out." },
    { word: "Opaque", definition: "Not able to be seen through; obscure." },
    { word: "Open", definition: "Allowing access; not closed." },
    { word: "Opening", definition: "An aperture or gap; a beginning." },
    { word: "Openly", definition: "Without concealment; publicly." },
    { word: "Opera", definition: "A dramatic work set to music." },
    { word: "Operate", definition: "To control the functioning of a machine." },
    { word: "Operation", definition: "An organized activity; a surgical procedure." },
    { word: "Opinion", definition: "A belief held without certainty." },
    { word: "Opinionated", definition: "Conceitedly assertive of one's opinions." },
    { word: "Opponent", definition: "A person who competes against another." },
    { word: "Opportune", definition: "Occurring at a favorable time." },
    { word: "Opportunity", definition: "A favorable time or occasion." },
    { word: "Oppose", definition: "To disapprove of and attempt to prevent." },
    { word: "Opposite", definition: "Completely different; facing something." },
    { word: "Opposition", definition: "Resistance or dissent; opposing group." },
    { word: "Oppress", definition: "To keep in hardship and distress." },
    { word: "Oppression", definition: "Prolonged cruel or unjust treatment." },
    { word: "Oppressive", definition: "Weighing heavily on the mind or senses." },
    { word: "Opt", definition: "To make a choice or decision." },
    { word: "Optical", definition: "Relating to sight or the eye." },
    { word: "Optimism", definition: "Hopefulness about the future." },
    { word: "Optimistic", definition: "Hopeful and confident about the future." },
    { word: "Optimize", definition: "To make the best use of something." },
    { word: "Option", definition: "A thing that is or may be chosen." },
    { word: "Optional", definition: "Available to be chosen; not required." },
    { word: "Opulent", definition: "Ostentatiously rich and luxurious." },
    { word: "Oral", definition: "Relating to the mouth; spoken." },

    // === P-Z (Words 986-1000) ===
    { word: "Pacify", definition: "To calm or soothe anger or agitation." },
    { word: "Pacific", definition: "Peaceful in character; relating to the Pacific Ocean." },
    { word: "Pacifist", definition: "A person who believes in peace over war." },
    { word: "Pact", definition: "A formal agreement between parties." },
    { word: "Paddle", definition: "A short oar; to walk barefoot in water." },
    { word: "Pagan", definition: "A person holding religious beliefs other than mainstream." },
    { word: "Pageant", definition: "An elaborate public spectacle or procession." },
    { word: "Pain", definition: "Physical suffering or discomfort." },
    { word: "Painful", definition: "Causing physical or mental hurt." },
    { word: "Painless", definition: "Not causing any pain." },
    { word: "Quaint", definition: "Attractively unusual or old-fashioned." },
    { word: "Quake", definition: "To shake or tremble violently." },
    { word: "Qualify", definition: "To become entitled to a benefit or privilege." },
    { word: "Quality", definition: "The standard of something as measured against others." },
    { word: "Quandary", definition: "A state of perplexity or uncertainty." },
    { word: "Radical", definition: "Relating to the fundamental nature of something; extreme." },
    { word: "Radiant", definition: "Sending out light; shining brightly." },
    { word: "Rage", definition: "Violent, uncontrollable anger." },
    { word: "Raid", definition: "A surprise attack to commit a crime." },
    { word: "Sacrifice", definition: "To give up something valued for a cause." },
    { word: "Sacred", definition: "Connected with God or a deity; holy." },
    { word: "Sadden", definition: "To cause to feel sad." },
    { word: "Tactful", definition: "Showing skill in dealing with sensitive matters." },
    { word: "Tactile", definition: "Relating to the sense of touch." },
    { word: "Talent", definition: "Natural aptitude or skill." },
    { word: "Ultimate", definition: "Being the best or most extreme of its kind." },
    { word: "Ultimatum", definition: "A final demand with a threat." },
    { word: "Ultrasonic", definition: "Relating to sound waves above human hearing." },
    { word: "Vacant", definition: "Having no fixtures or occupants; empty." },
    { word: "Vacate", definition: "To leave a place that was previously occupied." },
    { word: "Vacation", definition: "An extended period of leisure and recreation." },
    { word: "Wander", definition: "To walk or move in a leisurely manner." },
    { word: "Want", definition: "To have a desire for something." },
    { word: "War", definition: "A state of armed conflict between nations." },
    { word: "Xenial", definition: "Relating to hospitality between host and guest." },
    { word: "Xenon", definition: "A chemical element; a noble gas." },
    { word: "Xenophobia", definition: "Fear or hatred of foreigners." },
    { word: "Yacht", definition: "A medium-sized boat used for racing or recreation." },
    { word: "Yearn", definition: "To have an intense feeling of longing." },
    { word: "Yield", definition: "To produce or provide; to surrender." },
    { word: "Zeal", definition: "Great energy or enthusiasm in pursuit of a cause." },
    { word: "Zealot", definition: "A person who is fanatical about something." },
    { word: "Zenith", definition: "The highest point; peak." },
    { word: "Zephyr", definition: "A soft gentle breeze." },
    { word: "Zone", definition: "An area distinguished from surrounding areas." },
    { word: "Zoom", definition: "To move quickly; to change focal length." },
    { word: "Zany", definition: "Amusingly unconventional and idiosyncratic." },
    { word: "Zest", definition: "Great enthusiasm and energy; citrus peel." },
    { word: "Zealous", definition: "Having great energy or enthusiasm." },
    { word: "Zen", definition: "A state of calm and peacefulness." }
];